  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: time-checker-service
spec:
  ingressClassName: nginx
  rules:
  - host: "*.com"  # Wildcard host (adjust if needed)
    http:
      paths:
      - path: /current-time
        pathType: Prefix
        backend:
          service:
            name: time-checker-service
            port:
              number: 80




